---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies, automated, actions]
    groups:
      actions-all:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies, automated]
    commit-message:
      prefix: chore
      include: scope
    open-pull-requests-limit: 10
    groups:
      npm-dev-minor-patch:
        dependency-type: development
        patterns: ["*"]
        update-types: [minor, patch]
      npm-dev-major:
        dependency-type: development
        patterns: ["*"]
        update-types: [major]
      npm-runtime-minor-patch:
        dependency-type: production
        patterns: ["*"]
        update-types: [minor, patch]
      npm-runtime-major:
        dependency-type: production
        patterns: ["*"]
        update-types: [major]
